### ISSUE TITLE
Show branch probability

### ISSUE THREAD

**Issue by pautasso** [ilijagjorgjiev/RESTfulConversationMining#17]
For every XOR split, compute the frequency for each outgoing edge and display it as % on the corresponding outgoing edge.

**Comment by ilijagjorgjiev** [comment]
@pautasso I have computed the possibility and display it as %. This was done only at XORs, which have multiple outgoing edges since that is the only place it makes sense. For every other edge where there is no % written it is considered 100%. I don't display it since it just makes the picture more mess.
