### ISSUE TITLE
Show delay

### ISSUE THREAD

**Issue by pautasso** [ilijagjorgjiev/RESTfulConversationMining#18]
Compute the delay (time difference in ms) on each edge. If edges are executed multiple times (by different clients or repeated) store each delay in an array.

Display the average (or [min-max]) of the delay on each edge.

Color edges based on gradient calculated using the average delay.

**Comment by ilijagjorgjiev** [comment]
@pautasso I have stored all the delays and I am able to identify them and draw them on the graph.
1. When I draw them on the graph, the graph becomes too messy, so I think we should avoid drawing them at least at default.
2. For the gradient, since every avg is different it would become really messy since probably for bigger graphs there are going to be like 100 different avgs, which would result in really similar colors. My suggestion for this would be sth like to divide all the avgs like we did for the time periods maybe abs(minAvg-maxAvg)/2 and then use this for coloring hopefully, this won't result into many different gradient colors.
